service: image-rekon-bot 

custom:
  bucket: image-rekon-bot-images


provider:
  name: aws
  runtime: nodejs8.10
  profile: aws-private
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"  
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"
    
functions:
  handleCrc:
    handler: handleCrc.handler
    events:
      - http:
          path: webhook/twitter
          method: get
    environment:
      TWITTER_CONSUMER_SECRET: ${file(./serverless.env.yml):twitter.TWITTER_CONSUMER_SECRET}
  handleTweet:
    handler: handleTweet.handler
    events:
      - http:
          path: webhook/twitter
          method: post
    environment:
      BUCKET: ${self:custom.bucket} 
  respondToTweetWithImage:
    handler: respondToTweetWithImage.handler
    events:
      - s3: 
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*

